### PR TITLE
Add [tabindex]:not([tabindex="-1"]) to list of focusable elements

### LINKED ISSUE #5: DOM elements with tabindex="-1" should not be focusable
Focus trapping breaks when an element with `tabindex="-1"` is found in the within the trapper.
This bug is reproduced here:

https://ember-twiddle.com/bddd26d51b6fd1c2857134cc468e0562?openFiles=templates.application.hbs%2C

### PR DESCRIPTION
**Pull request by hakilebara**
Fixes #5

### CODE REVIEW

**Comment by hakilebara** [comment]
ping @steveszc

**Comment by steveszc** [comment]
Sorry for the delay on this. Thanks for the contribution.

**Comment by hakilebara** [comment]
Would it be possible to release a new version of the addon on npm?

**Comment by steveszc** [comment]
@hakilebara  `0.3.0` is now published https://www.npmjs.com/package/ember-focus-trapper

**Pull request merged**
